#!/bin/bash
# Hermes Desktop App Launcher with MLX Integration
# Monitored process - auto-restarts on crash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AGENT_NAME="hermes-desktop"
PID_FILE="/tmp/${AGENT_NAME}.pid"
LOG_FILE="${SCRIPT_DIR}/../../logs/${AGENT_NAME}.log"
LOCK_FILE="/tmp/${AGENT_NAME}.lock"

# Configuration
MLX_HOST="${MLX_HOST:-127.0.0.1}"
MLX_PORT="${MLX_PORT:-8090}"
MLX_URL="http://${MLX_HOST}:${MLX_PORT}/v1"
MODEL_ID="${HERMES_MODEL:-mlx-community/Hermes-3-Llama-3.1-8B-4bit}"

# Ensure log directory
mkdir -p "$(dirname "$LOG_FILE")"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"
}

# Prevent multiple instances
if [ -f "$LOCK_FILE" ]; then
    OLD_PID=$(cat "$LOCK_FILE" 2>/dev/null || echo "")
    if [ -n "$OLD_PID" ] && kill -0 "$OLD_PID" 2>/dev/null; then
        log "Hermes desktop already running on PID $OLD_PID"
        echo "$OLD_PID" > "$PID_FILE"
        exit 0
    else
        rm -f "$LOCK_FILE"
    fi
fi

# Cleanup on exit
cleanup() {
    log "Shutting down Hermes desktop..."
    rm -f "$PID_FILE" "$LOCK_FILE"
    exit 0
}
trap cleanup SIGTERM SIGINT EXIT

# Check if MLX server is running - wait for it
wait_for_mlx() {
    local max_attempts=30
    local attempt=0
    
    log "Waiting for MLX server at $MLX_URL..."
    
    while [ $attempt -lt $max_attempts ]; do
        if curl -s "$MLX_URL/models" >/dev/null 2>&1; then
            log "MLX server is ready!"
            return 0
        fi
        attempt=$((attempt + 1))
        log "Waiting for MLX... ($attempt/$max_attempts)"
        sleep 2
    done
    
    log "ERROR: MLX server not responding at $MLX_URL"
    log "Start it with: ./agents/hermes-3-mlx/hermes-mlx-server.sh"
    return 1
}

# Configure Hermes to use MLX endpoint
configure_hermes() {
    local config_dir="$HOME/.config/hermes"
    local config_file="$config_dir/config.yaml"
    
    mkdir -p "$config_dir"
    
    # Create/update config to use local MLX
    cat > "$config_file" <>CONFIG
model:
  provider: "custom"
  default: "$MODEL_ID"
  base_url: "$MLX_URL"
  context_length: 131072
  
# Hermes Desktop Config
# Auto-generated by Dr.Fixit Agent System
# MLX Backend: $MLX_URL
CONFIG

    log "Hermes configured to use MLX at $MLX_URL"
    log "Model: $MODEL_ID"
}

# Main launch sequence
main() {
    log "=== Hermes Desktop Launcher Starting ==="
    
    # Step 1: Start MLX if not running
    if ! curl -s "$MLX_URL/models" >/dev/null 2>&1; then
        log "MLX server not running. Starting it..."
        "$SCRIPT_DIR/../hermes-3-mlx/hermes-mlx-server.sh" &
        sleep 5
    fi
    
    # Step 2: Wait for MLX
    if ! wait_for_mlx; then
        log "Failed to connect to MLX. Exiting."
        exit 1
    fi
    
    # Step 3: Configure Hermes endpoint
    configure_hermes
    
    # Step 4: Launch Hermes Desktop
    log "Starting Hermes Desktop App..."
    
    # Set lock file
    echo $$ > "$LOCK_FILE"
    
    # Get actual hermes binary path
    HERMES_BIN="${HERMES_BIN:-$(which hermes)}"
    
    if [ -z "$HERMES_BIN" ]; then
        log "ERROR: hermes command not found"
        log "Install with: pip install hermes-agent"
        exit 1
    fi
    
    log "Using Hermes binary: $HERMES_BIN"
    
    # Launch desktop app and capture PID
    "$HERMES_BIN" &
    HERMES_PID=$!
    
    # Write PID for monitoring
    echo "$HERMES_PID" > "$PID_FILE"
    
    log "Hermes Desktop started (PID: $HERMES_PID)"
    log "Connected to MLX at $MLX_URL"
    log "Logs: $LOG_FILE"
    
    # Monitor the process
    wait $HERMES_PID
    EXIT_CODE=$?
    
    log "Hermes Desktop exited with code $EXIT_CODE"
    
    # Cleanup
    rm -f "$PID_FILE" "$LOCK_FILE"
    
    exit $EXIT_CODE
}

# Health check function (called by heartbeat monitor)
case "${1:-}" in
    --health-check)
        # Check if process exists
        if [ -f "$PID_FILE" ]; then
            PID=$(cat "$PID_FILE" 2>/dev/null || echo "")
            if [ -n "$PID" ] && kill -0 "$PID" 2>/dev/null; then
                echo "healthy"
                exit 0
            fi
        fi
        echo "unhealthy"
        exit 1
        ;;
    *)
        main
        ;;
esac
