export const VMS = [
  {
    id: 0,
    app: "super-agents",
    name: "Super Agents",
    icon: "⚡",
    region: "jnb",
    cpu: 1,
    mem: 1024,
    role: "Single hub · Command API · Hermes/Nous · OpenAI · MiMo · Discord/Slack",
    isHub: true,
  },
  {
    id: 1,
    app: "studex-n8n",
    name: "n8n Automation",
    icon: "🖥️",
    region: "jnb",
    cpu: 1,
    mem: 512,
    role: "Workflows · Stitch · provisioning",
  },
  {
    id: 2,
    app: "studex-claude-code",
    name: "Claude Code Agent",
    icon: "🤖",
    region: "jnb",
    cpu: 2,
    mem: 2048,
    role: "Autonomous Coding Agent · Claude CLI",
  },
  {
    id: 3,
    app: "studex-cursor-agent",
    name: "Cursor Agent",
    icon: "🎯",
    region: "jnb",
    cpu: 2,
    mem: 4096,
    role: "AI Pair Programmer · VS Code in Browser",
  },
  {
    id: 4,
    app: "studex-openclaw",
    name: "OpenClaw Gateway",
    icon: "⚡",
    region: "jnb",
    cpu: 2,
    mem: 2048,
    role: "Agent Runtime · All 8 Super Agents · Redis",
  },
  {
    id: 5,
    app: "studex-portal",
    name: "Client Portal",
    icon: "🌐",
    region: "jnb",
    cpu: 1,
    mem: 1024,
    role: "VM 5 · Jarvis Chat · Signup · Speech-to-Text",
  },
]

export const VM_LOGS = {
  0: [
    { t: "10:00", type: "system", msg: "Super Agents hub — /health OK · inventory ready" },
    { t: "10:05", type: "agent", msg: "Daytona sandbox Super Agents — OpenClaw + CashClaw bootstrap" },
    { t: "10:12", type: "agent", msg: "Hermes-4-70B route → Nous inference API" },
    { t: "10:18", type: "system", msg: "Discord/Slack bridges idle until tokens set on Fly" },
  ],
  1: [
    { t: "09:14", type: "system", msg: "n8n workflow triggered — Stitch payment received" },
    { t: "09:15", type: "agent", msg: "Provisioning pipeline started for RetailBot — The Butcher Shop" },
    { t: "09:17", type: "system", msg: "Supabase record created — client email: john@butchershop.co.za" },
    { t: "09:18", type: "mail", msg: "Welcome email sent via Resend — naledi@thebutchershop.superagents.co.za" },
    { t: "09:19", type: "slack", msg: "#new-commissions notified — R3,500 · RetailBot · The Butcher Shop" },
    { t: "11:32", type: "mail", msg: "Inbound email received — naledi@thebutchershop.superagents.co.za" },
    { t: "11:33", type: "agent", msg: "OpenClaw processed email — reply sent in 4.2s" },
    { t: "14:50", type: "system", msg: "Supabase daily backup completed — 847 records" },
    { t: "18:00", type: "system", msg: "n8n daily report workflow executed" },
  ],
  2: [
    { t: "08:00", type: "agent", msg: "Claude Code Agent initialised — workspace /workspace ready" },
    { t: "10:15", type: "code", msg: "Task received: Fix command-center build error — eslint missing" },
    { t: "10:16", type: "code", msg: "package.json updated — eslint + eslint-config-next added" },
    { t: "10:18", type: "code", msg: "git commit: Fix: add eslint for Vercel build — pushed" },
    { t: "10:22", type: "system", msg: "Vercel auto-deploy triggered — build successful" },
    { t: "13:40", type: "code", msg: "Task received: Add Obsidian Brain sphere to command-center" },
    { t: "13:41", type: "code", msg: "Three.js component scaffolded — /src/components/BrainSphere.tsx" },
    { t: "13:55", type: "code", msg: "Component complete — 340 lines · tests passing" },
  ],
  3: [
    { t: "09:00", type: "system", msg: "Cursor Agent VM started — code-server running on :8080" },
    { t: "09:05", type: "code", msg: "Workspace loaded — studex-platform repository" },
    { t: "10:30", type: "code", msg: "Agent Forge component opened — refactoring suit card layout" },
    { t: "11:45", type: "code", msg: "Mobile responsive fixes applied — agent grid breakpoints updated" },
    { t: "14:20", type: "code", msg: "VM5 portal reviewed — Jarvis chat improvements suggested" },
    { t: "16:00", type: "system", msg: "Auto-save completed — workspace snapshot taken" },
  ],
  4: [
    {
      t: "00:00",
      type: "agent",
      msg: "All 8 agents online — RetailBot · HealthBot · PropBot · DineAssist · ProAssist · SalesCloser · MultiBot · TradeBot",
    },
    { t: "01:14", type: "agent", msg: "Naledi (RetailBot) — 23:14 conversation — cart recovery R627" },
    { t: "02:03", type: "agent", msg: "Office (ProAssist) — 02:03 email processed — intake form sent" },
    { t: "08:14", type: "agent", msg: "Close (SalesCloser) — 40 outbound calls initiated" },
    { t: "08:47", type: "agent", msg: "Close — 6 meetings booked — pipeline updated" },
    { t: "11:32", type: "agent", msg: "Naledi — inbound WhatsApp processed — wagyu query answered" },
    { t: "14:00", type: "system", msg: "Redis memory: 128MB used — 847 active sessions" },
    { t: "23:59", type: "system", msg: "Daily log saved — 847 total conversations · R18,420 revenue attributed" },
  ],
  5: [
    { t: "09:00", type: "system", msg: "VM5 portal running — app.stud.exchange · health check OK" },
    { t: "10:15", type: "jarvis", msg: "Jarvis conversation — prospect: retail business, Cape Town" },
    { t: "10:18", type: "jarvis", msg: "Agent recommendation: RetailBot · quick reply selected" },
    { t: "10:22", type: "signup", msg: "Signup initiated — Company: Fresh Produce Market · email captured" },
    { t: "10:24", type: "signup", msg: "Commission submitted — R3,500 RetailBot — routed to Stitch" },
    { t: "10:28", type: "jarvis", msg: "Jarvis speech-to-text used — language: Afrikaans detected" },
    { t: "14:33", type: "jarvis", msg: "Support query — existing client, HealthBot questions" },
    { t: "14:35", type: "jarvis", msg: "Query resolved — Northstar link resent" },
  ],
}

export const BRAIN_NODES = [
  { id: 1, label: "Studex Africa Tour — 6 countries, 16+ partners", cat: "strategy", hot: true },
  { id: 2, label: "Super Agents R100M revenue target — Dec 2026", cat: "revenue", hot: true },
  { id: 3, label: "KASM + Fly.io provisioning architecture", cat: "tech", hot: false },
  { id: 4, label: "Victor Ndlovu — Partner Director", cat: "team", hot: false },
  { id: 5, label: "Stitch Express — primary SA payment gateway", cat: "payment", hot: false },
  { id: 6, label: "Cloudflare Tunnel — Mac Mini → public endpoints", cat: "infra", hot: true },
  { id: 7, label: "Northstar Framework — soul-giving ritual", cat: "product", hot: true },
  { id: 8, label: "KuCoin JV — FSCA CASP licensed exchange", cat: "partners", hot: false },
  { id: 9, label: "Kate — engaged, 10+ years, Egypt April 2026", cat: "personal", hot: false },
  { id: 10, label: "Wagyu Biltong Gold — 52g protein, Halaal certified", cat: "product", hot: false },
  { id: 11, label: "Mac Mini M4 Pro — primary server, port 4000", cat: "infra", hot: false },
  { id: 12, label: "Naledi + Emily van Dewild — AI personas", cat: "agents", hot: true },
  { id: 13, label: "Supabase local — port 54321 — all client records", cat: "tech", hot: false },
  { id: 14, label: "n8n Docker — port 5678 — provisioning pipeline", cat: "tech", hot: false },
  { id: 15, label: "stud.exchange — GoDaddy domain — Vercel hosted", cat: "infra", hot: true },
  { id: 16, label: "OpenClaw port 3000 — WhatsApp bridge active", cat: "tech", hot: false },
  { id: 17, label: "Wildberries + NtechLab — Russian partners", cat: "partners", hot: false },
  { id: 18, label: "Animal Exchange — blockchain wildlife conservation", cat: "product", hot: false },
]
